### ISSUE TITLE
Questions about rebuilding the project, Why is it wrong in that photo？

### ISSUE THREAD

**Issue by bonjourdrs** [Joaquin-aliaga/bioPDSN#2]
(OFR) test@DISP-301:~/PycharmProjects/DAI/OFD/bioPDSN$ python biopdsn_train.py -num_class 403 -dfPath "./lib/data/dataframe.pickle" -rw "./weights/model-r50-am-lfw/model,00" --batch_size 64
loading ./weights/model-r50-am-lfw/model 0
[22:33:22] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.12.1. Attempting to upgrade...
[22:33:22] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2020-12-15 22:33:26.186111: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/home/test/TensorRT-7.0.0.11/lib
2020-12-15 22:33:26.186126: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

  | Name       | Type                | Params
---------------------------------------------------
0 | loss_cls   | CrossEntropyLoss    | 0     
1 | loss_diff  | L1Loss              | 0     
2 | classifier | MarginCosineProduct | 206 K 
3 | sia        | Sequential          | 2.4 M 
4 | fc         | Sequential          | 12.9 M
---------------------------------------------------
15.5 M    Trainable params
0         Non-trainable params
15.5 M    Total params
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "biopdsn_train.py", line 55, in <module>
    trainer.fit(biopdsn)
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 66, in train
    results = self.train_or_test()
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 65, in train_or_test
    results = self.trainer.train()
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 593, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/test/.conda/envs/OFR/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/test/PycharmProjects/DAI/OFD/bioPDSN/lib/data/rmfd_dataset.py", line 28, in __getitem__
    source = cv2.imdecode(np.fromfile(row['source'], dtype=np.uint8), cv2.IMREAD_UNCHANGED)
FileNotFoundError: [Errno 2] No such file or directory: 'self-built-masked-face-recognition-dataset/AFDB_face_dataset/zhaoyouting/1_0_zhaoyouting_0128.jpg'

**Comment by bonjourdrs** [comment]
The path is right, and other photos are also fine, but it happened in that place. Can you provide details of your library environment requirements?

**Comment by bonjourdrs** [comment]
so glad to see the Usefull guides. But I can‘t  get the requirements(wget from Drive (large)file). Can you send the requirements.txt to me? Thank you. the email: drsseu@qq.com

**Comment by bonjourdrs** [comment]
"Connecting to docs.google.com (docs.google.com)|172.217.26.142|:443... failed: Unknown error.
Retrying"

So I can't get the requirements!!!
Thank you!!

**Comment by bonjourdrs** [comment]
I saw your update, but the project still has previous errors. Can you send me the requirements? thank you so much!

**Comment by Joaquin-aliaga** [comment]
Hi. 
You may misunderstood, the [Drive file](https://drive.google.com/file/d/1UlOk6EtiaXTHylRUx2mySgvJX9ycoeBp/view) contains the RMFD dataset. Not the requirements.

To get the requirements.txt just install pipreqs `pip install pipreqs` and run `pipreqs .` inside bioPDSN.

However my requirements.txt is:
mxnet-cu101
torchvision==0.8.1
easydict==1.9
torch==1.7.0
opencv_python==4.4.0.46
tqdm==4.53.0
numpy==1.19.4
facenet_pytorch==2.5.1
pandas==1.1.5
Pillow==8.0.1
pytorch_lightning==1.1.1
scikit_learn==0.23.2

**Comment by Joaquin-aliaga** [comment]
> source = cv2.imdecode(np.fromfile(row['source'], dtype=np.uint8), cv2.IMREAD_UNCHANGED)
> FileNotFoundError: [Errno 2] No such file or directory: 'self-built-masked-face-recognition-dataset/AFDB_face_dataset/zhaoyouting/1_0_zhaoyouting_0128.jpg'

Do you still have this issue?
I think the problem is the path to the img, i recently add a getcwd() to get the working directory and added it to the img path as an argument, you can see the changes if you pull my last updates.

**Comment by bonjourdrs** [comment]
Thanks， I can train the net now, but I cannot run the test yet. It seems that the weights are not saved after training. And I can't call GPU for training, although it can read cuda device 0.

**Comment by Joaquin-aliaga** [comment]
I tried training in Google Colab and also in a GCP instance and in both I call GPU successfully for training, so you may need to check your system configuration.

About the weights, check which metric are you monitoring inside the callback. I tried with val accuracy occ and it works.

The biopdsn_test code isn't finished yet. You may need to implement it by yourself.

**Comment by bonjourdrs** [comment]
Thank you，I will try it!!! Can rearch the accuracy  in the paper?
